- hosts: localhost
  gather_facts: no
  become: n
  
  vars_files:
          - /etc/ansible/vault.yml
  vars:
          image_name: "appfinalproject"
          image_tag: "v04"
          ports: "5002"
          repo_name: "https://github.com/MihailDDimovski/DEVOPS"
          branch_name: "full_work_flow"
          docker_repo: "mihaildanailovdimovski/finalproject"
          code_directory: "/home/misho/project/DEVOPS"
  tasks:
          - name: Get the code from GitHub
            git:
               repo: "{{ repo_name }}"
               version: "{{ branch_name }}"
               dest: "{{ code_directory }}"   
          - name: log into docker hub registry
            docker_login:
               username: "{{ myu }}"
               password: "{{ myp }}"
          - name: build container image and push to DockerHub
            docker_image:
               name: "{{ image_name }}"
               tag: "{{ image_tag }}"
               build:
                 path: /app/home/misho/project/DEVOPS
               source: build
               state: present
               repository: "{{ docker_repo }}:{{ image_tag }}"
               push: true
          - name: ensure a container is running
            docker_container:
               name: "{{ image_name }}"
               state: started
               image: "{{ docker_repo }}:{{ image_tag }}"
               pull: true
               ports:
                 - "{{ ports }}"

